apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounting
  namespace: haidelbert
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      containers:
        - env:
            - name: AWS_S3_DISABLE_SSL
              value: ""
            - name: AWS_S3_ENDPOINT
              value: ""
            - name: AWS_S3_FORCE_PATH_STYLE
              value: "true"
            - name: AWS_S3_ID
              value: ""
            - name: AWS_S3_RECEIPT_BUCKET
              value: ""
            - name: AWS_S3_REGION
              value: ""
            - name: AWS_S3_SECRET
              value: ""
            - name: CLIENT_AFS_SERVICE
              value: ""
            - name: CLIENT_VAT_SERVICE
              value: ""
            - name: ENV
              value: ""
            - name: JWT_PUBLIC_KEY
              value: ""
            - name: KAFKA_SERVERS
              value: ""
            - name: POSTGRES_DB
              value: ""
            - name: POSTGRES_HOST
              value: ""
            - name: POSTGRES_PASSWORD
              value: ""
            - name: POSTGRES_PORT
              value: ""
            - name: POSTGRES_USER
              value: ""
          image: haidelbert/accounting:latest
          imagePullPolicy: Always
          name: accounting
          ports:
            - containerPort: 9091
              name: 9091tcp02
              protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
