apiVersion: apps/v1
kind: Deployment
metadata:
  name: vat
  namespace: haidelbert
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      containers:
        - env:
            - name: ACCOUNTINGCLIENT_MP-REST_URL
              value: ""
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: ""
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: ""
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: ""
            - name: VAT_ACCOUNTING_CREDENTIALS_PASSWORD
              value: ""
          image: haidelbert/vat:d78a815e50abbd2ed1b6f64651015bbf9de281a4
          imagePullPolicy: Always
          name: vat
          ports:
            - containerPort: 8080
              name: 8080tcp02
              protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
