version: '3'
services:
  user-mongo:
    image: 'mongo'
    container_name: 'dev-mongo-container'
    environment:
      - MONGO_INITDB_DATABASE=user
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
  accounting-postgres:
    image: postgres
    container_name: 'accounting-postgres'
    environment:
      - POSTGRES_DB=accounting
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres-volume:/var/lib/postgresql/data
    ports:
      - 5433:5432
