version: '3'
services:
  haidelbert-postgres-dev:
    image: postgres
    environment:
      - POSTGRES_DB=haidelbert
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./dev-haidelbert-postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
  hasura-accounting:
    image: hasura/graphql-engine
    ports:
    - "8080:8080"
    depends_on:
    - "haidelbert-postgres-dev"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:root@haidelbert-postgres-dev:5432/haidelbert
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: root
  minio1:
    image: minio/minio:RELEASE.2020-08-18T19-41-00Z
    container_name: 'dev-minio1-container'
    volumes:
      - dev-data1-1:/data1
      - dev-data1-2:/data2
    ports:
      - "9190:9000"
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password
    command: server http://minio{1...2}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  minio2:
    image: minio/minio:RELEASE.2020-10-09T22-55-05Z
    container_name: 'dev-minio2-container'
    volumes:
      - dev-data2-1:/data1
      - dev-data2-2:/data2
    ports:
      - "9191:9000"
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password
    command: server http://minio{1...2}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
volumes:
  dev-data1-1:
  dev-data1-2:
  dev-data2-1:
  dev-data2-2:
