apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 3
  name: user
  namespace: haidelbert
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      containers:
        - env:
            - name: ENV
              value: staging
            - name: JWT_EXPIRY_SECONDS
              value: "3600"
            - name: JWT_PRIVATE_KEY
              value: ?
            - name: JWT_PUBLIC_KEY
              value: ?
            - name: mongoUrl
              value: ?
          image: haidelbert/user:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 3
            successThreshold: 1
            tcpSocket:
              port: 9090
            timeoutSeconds: 4
          name: user
          ports:
            - containerPort: 9090
              name: 9090tcp02
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 3
            successThreshold: 2
            tcpSocket:
              port: 9090
            timeoutSeconds: 4
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
