on:
  push:
    paths:
    - 'annual-financial-statements/**'
    - '.github/workflows/ci-annual-financial-statements.yml'
name: CI/CD Annual Financial Statements
jobs:
  build-annual-financial-statements:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql user: postgres
          postgresql password: root
          postgresql db: annual-financial-statements_test
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up jdk11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Migrate Test DB
        working-directory: annual-financial-statements
        run: ./mvnw resources:resources liquibase:update -Ptest
      - name: Test
        working-directory: annual-financial-statements
        run: ./mvnw surefire:test -Dquarkus-profile=test -Ptest
      - name: Build Native
        working-directory: annual-financial-statements
        run: ./mvnw package -Pnative -Dquarkus.native.container-build=true -Dliquibase.should.run=false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./annual-financial-statements/src/main/docker/Dockerfile
          context: ./annual-financial-statements
          tags: |
            haidelbert/annual-financial-statements:${{ github.sha }}
            haidelbert/annual-financial-statements:latest
          push: true
  deploy-annual-financial-statements-staging:
    runs-on: ubuntu-latest
    needs: build-annual-financial-statements
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: deploy to cluster
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: set image deployment/annual-financial-statements annual-financial-statements=haidelbert/annual-financial-statements:${{ github.sha }} --record --namespace haidelbert --context staging --insecure-skip-tls-verify=true
      - name: verify deployment
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "1.15"
        with:
          args: rollout status deployment/annual-financial-statements --namespace haidelbert --context staging --insecure-skip-tls-verify=true
