on:
  push:
    paths:
    - 'frontend/**'
    - '.github/workflows/ci-frontend.yml'
name: CI/CD Frontend
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Prepare CI
        run: chmod +x ./infra/ci/waitForPort.sh
      - name: Test Frontend
        run: |
          npm ci
          (npm run start&)
          npm run lint
          npm run test
          ./../infra/ci/waitForPort.sh 4200
          npm run cypress:run
        working-directory: frontend
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          tags: |
            haidelbert/frontend:${{ github.sha }}
            haidelbert/frontend:latest
          push: true
  deploy-frontend-staging:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - name: deploy to cluster
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: set image deployment/frontend frontend=haidelbert/frontend:${{ github.sha }} --record --namespace haidelbert --context staging --insecure-skip-tls-verify=true
      - name: verify deployment
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "1.15"
        with:
          args: rollout status deployment/frontend --namespace haidelbert --context staging --insecure-skip-tls-verify=true
