on:
  push:
    paths:
    - 'register-of-assets/**'
    - '.github/workflows/ci-register-of-assets.yml'
name: CI/CD Register of Assets
jobs:
  build-register-of-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql user: postgres
          postgresql password: root
          postgresql db: register-of-assets_test
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Test
        run: npm ci && npm run test
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./register-of-assets/Dockerfile
          context: ./register-of-assets
          tags: |
            haidelbert/register-of-assets:${{ github.sha }}
            haidelbert/register-of-assets:latest
          push: true
  deploy-register-of-assets-staging:
    runs-on: ubuntu-latest
    needs: build-register-of-assets
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: deploy to cluster
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: set image deployment/register-of-assets register-of-assets=haidelbert/register-of-assets:${{ github.sha }} --record --namespace haidelbert --context staging --insecure-skip-tls-verify=true
      - name: verify deployment
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "1.15"
        with:
          args: rollout status deployment/register-of-assets --namespace haidelbert --context staging --insecure-skip-tls-verify=true
