on:
  push:
    paths:
    - 'user/**'
    - '.github/workflows/ci-user.yml'
name: CI/CD User
jobs:
  build-user:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Start MongoDB 4.2
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2
      - name: Migrate test DB
        run: ENV=ci go run ./cmd/migration/migration.go
        working-directory: user
      - name: Test
        run: ENV=ci go test ./...
        working-directory: user
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./user/Dockerfile
          context: ./user
          tags: |
            haidelbert/user:${{ github.sha }}
            haidelbert/user:latest
          push: true
  deploy-user-staging:
    runs-on: ubuntu-latest
    needs: build-user
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Migrate staging DB
        run: ENV=staging mongoUrl=${{ secrets.MONGOURLSTAGING }} go run ./cmd/migration/migration.go
        working-directory: user
      - name: deploy to cluster
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: set image deployment/user user=haidelbert/user:${{ github.sha }} --record --namespace haidelbert --context staging --insecure-skip-tls-verify=true
      - name: verify deployment
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "1.15"
        with:
          args: rollout status deployment/user --namespace haidelbert --context staging --insecure-skip-tls-verify=true
