on:
  push:
    paths:
    - 'vat/**'
    - '.github/workflows/ci-vat.yml'
name: CI/CD VAT
jobs:
  build-vat:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql user: postgres
          postgresql password: root
          postgresql db: vat
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up jdk11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build Native
        working-directory: vat
        run: ./mvnw package -Pnative -Dquarkus.native.container-build=true -Dliquibase.should.run=false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./vat/src/main/docker/Dockerfile.native
          context: ./vat
          tags: |
            haidelbert/vat:${{ github.sha }}
            haidelbert/vat:latest
          push: true
  deploy-vat-staging:
    runs-on: ubuntu-latest
    needs: build-vat
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: deploy to cluster
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: set image deployment/vat vat=haidelbert/vat:${{ github.sha }} --record --namespace haidelbert --context staging --insecure-skip-tls-verify=true
      - name: verify deployment
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "1.15"
        with:
          args: rollout status deployment/vat --namespace haidelbert --context staging --insecure-skip-tls-verify=true
